development:
  secret_token: ENV['SECRETE_TOKEN']
  secret_key_base: ENV['SECRETE_KEY_BASE']
production:
  secret_token: ENV['SECRETE_TOKEN']
  secret_key_base: ENV['SECRETE_KEY_BASE']
test:
  secret_token: ENV['SECRETE_TOKEN']
  secret_key_base: ENV['SECRETE_KEY_BASE']